spring.application.name=ChatApp-Backend

spring.datasource.url=jdbc:mysql://localhost:3306/chatapp
spring.datasource.username=root
spring.datasource.password=VIRAT@018

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.google.client-id=649729963788-p7ov2u0t808tbnaevqge8g4bjdv09fpp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email